// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/5/2026, 2:05:24 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/juan/Documents/github/juanmiguelar/LaChozaDeLe-a/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/juan/Documents/github/juanmiguelar/LaChozaDeLe-a/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/juan/Documents/github/juanmiguelar/LaChozaDeLe-a/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/juan/Documents/github/juanmiguelar/LaChozaDeLe-a/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/juan/Documents/github/juanmiguelar/LaChozaDeLe-a/plugins/**/*.{js,ts,mjs}","/Users/juan/Documents/github/juanmiguelar/LaChozaDeLe-a/composables/**/*.{js,ts,mjs}","/Users/juan/Documents/github/juanmiguelar/LaChozaDeLe-a/utils/**/*.{js,ts,mjs}","/Users/juan/Documents/github/juanmiguelar/LaChozaDeLe-a/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/juan/Documents/github/juanmiguelar/LaChozaDeLe-a/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/juan/Documents/github/juanmiguelar/LaChozaDeLe-a/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/juan/Documents/github/juanmiguelar/LaChozaDeLe-a/app.config.{js,ts,mjs}"]}},
{"darkMode":"class","theme":{"extend":{"colors":{"primary":"#d97706","background-light":"#f5f5f4","background-dark":"#0c0a09","surface-light":"#ffffff","surface-dark":"#1c1917","text-main-light":"#1c1917","text-main-dark":"#f5f5f4","text-muted-light":"#57534e","text-muted-dark":"#a8a29e"},"fontFamily":{"display":["Playfair Display","serif"],"body":["Lato","sans-serif"]},"borderRadius":{"DEFAULT":"0.5rem","xl":"1rem","2xl":"1.5rem"}}}}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;